DROP TABLE IF EXISTS TODO_ITEMS;

CREATE TABLE TODO_ITEMS (
  id LONG AUTO_INCREMENT  PRIMARY KEY,
  item_desc VARCHAR(250) NOT NULL,
  tag_name VARCHAR(250) DEFAULT NULL,
  reminder VARCHAR(250) DEFAULT NULL,
  status VARCHAR(250) DEFAULT 'OPEN',
  modified_on DATE
  
);
