DROP TABLE IF EXISTS TODO_ITEMS;

CREATE TABLE TODO_ITEMS (
  id LONG AUTO_INCREMENT PRIMARY KEY,
  item_desc VARCHAR(250) NOT NULL,
  tag_name VARCHAR(250) DEFAULT NULL,
  reminder DATE DEFAULT NULL,
  IS_DONE NUMBER(1,0) DEFAULT 0,
  modified_on DATE DEFAULT SYSDATE
);
